### ISSUE TITLE
Voice element

### ISSUE THREAD

**Issue by duncanmcclean** [Techworker/ssml#1]
I'm attempting to use this package to generate ssml to go into Azure's text to speech system.

However, I need to specify a `voice` element. https://www.w3.org/TR/speech-synthesis11/#S3.2.1

How would I go around doing it?

**Comment by Techworker** [comment]
Hi, either use a `Custom` Element (see readme) or create a pull request for a new voice element.

**Comment by Techworker** [comment]
@damcclean I updated the lib and added 5 new elements:
 - `amazon:effect`
 - `voice`
 - `emphasis`
 - `sub`
 - `prosody`

But its mostly from the alexa spec, so you'll need to add the extra voice attributes from the spec on your own while building:

```php
SsmlBuilder::factory()->voice('Matthew')->attr('language', '..')->attr('X', 'Y'); // and so on
```

**Comment by duncanmcclean** [comment]
Nice, thanks.
